//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCompanyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProviderProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProviderProduct()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int providerProductID { get; set; }
        public int prodID { get; set; }
        public int provID { get; set; }
        public int provId { get; set; }
        public int prodId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public virtual tblProduct tblProduct1 { get; set; }
        public virtual tblProvider tblProvider1 { get; set; }
    }
}
