//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCompanyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblProviderProducts1 = new HashSet<tblProviderProduct>();
        }
    
        public int productID { get; set; }
        public string name { get; set; }
        public int producerID { get; set; }
        public decimal price { get; set; }
        public int categoryID { get; set; }
        public string details { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblProducer tblProducer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProviderProduct> tblProviderProducts1 { get; set; }
    }
}
