//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCompany.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSupplier()
        {
            this.tblSupplierProducts = new HashSet<tblSupplierProduct>();
        }
    
        public int supplierId { get; set; }
        public string name { get; set; }
        public int rating { get; set; }
        public Nullable<bool> isOrganization { get; set; }
        public bool isBlocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplierProduct> tblSupplierProducts { get; set; }
    }
}
