//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeCompany.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierProduct
    {
        public int SupProdId { get; set; }
        public int supplierID { get; set; }
        public int productID { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
